language: python
python:
    - "2.7"
#Instalar dependencias
install:
    - pip install pytest pytest-cov
    - pip install mockito
    - pip install coveralls
    - pip install pep8
    - pip install radon
script:
    - py.test --cov . --cov-report term-missing
    - radon cc src/.
    - radon mi src/.
    - radon raw src/.
    - radon cc tests/.
    - radon mi tests/.
    - radon raw tests/.
    - pep8 src/.
    - pep8 tests/.
after_success:
    - coveralls
notifications:
    email:
        recipients:
            - laurixi1993@hotmail.com
        on_failure: always